version: '3.6'

services:
  traefik:
    image: traefik:v2.9.4
    container_name: traefik
    networks:
      - traefik-net
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=christiancazu@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    volumes:
      - "./.volumes/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    networks:
      - traefik-net
    environment:
      - VITE_API_URL="https://fakestoreapis.com"
    ports:
      - 3000:3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`prueba-tecnicax.localhost`)'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.tls.certresolver=myresolver'

networks:
  traefik-net:
    external: true

volumes:
  cache:
    driver: local
